apiVersion: v1
kind: Namespace
metadata:
  name: wind-power
  labels:
    name: wind-power
    app.kubernetes.io/name: wind-power
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes