"""Restructured models using models package

Revision ID: fffbfaf3fca1
Revises: 
Create Date: 2025-04-03 17:45:19.758279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fffbfaf3fca1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('training_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.execute('DROP INDEX IF EXISTS idx_training_history_created_at')
    op.execute('DROP INDEX IF EXISTS idx_training_history_file_id')
    op.execute('DROP INDEX IF EXISTS idx_training_history_user_id')
    op.execute('CREATE INDEX IF NOT EXISTS ix_training_history_file_id ON training_history (file_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_training_history_user_id ON training_history (user_id)')
    op.execute('ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP')
    op.execute('ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'updated_at')
    op.drop_column('user_roles', 'created_at')
    op.drop_index(op.f('ix_training_history_user_id'), table_name='training_history')
    op.drop_index(op.f('ix_training_history_file_id'), table_name='training_history')
    op.create_index('idx_training_history_user_id', 'training_history', ['user_id'], unique=False)
    op.create_index('idx_training_history_file_id', 'training_history', ['file_id'], unique=False)
    op.create_index('idx_training_history_created_at', 'training_history', [sa.text('created_at DESC')], unique=False)
    op.alter_column('training_history', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('training_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
