FROM c104-scada-client:v1.0

WORKDIR /app

COPY simulation/scada-simulator/scada_multifarm.py .

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

CMD ["python3", "scada_multifarm.py"]
