apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: kong
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
        - name: KONG_LOG_LEVEL
          value: "debug"
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "2"