# Redis Sentinel configuration
bind 0.0.0.0
port 26379
daemonize no
pidfile /var/run/redis-sentinel.pid
logfile ""
dir /tmp
sentinel announce-ip sentinel
sentinel announce-port 26379
sentinel monitor mymaster redis-master 6379 2
sentinel auth-pass mymaster redis123
sentinel down-after-milliseconds mymaster 30000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 180000
sentinel deny-scripts-reconfig yes