FROM continuumio/miniconda3

RUN apt-get update && apt-get install -y curl postgresql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY environment.yml .

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip config set global.trusted-host mirrors.aliyun.com

RUN conda env create -f environment.yml && conda clean --all --yes

ENV PATH /opt/conda/envs/wind-power-env/bin:$PATH

RUN pip install celery redis flower

COPY . /app/

ENTRYPOINT ["celery", "-A", "celery_app.celery_app"]
CMD ["worker", "--loglevel=info", "--concurrency=2"]
