INSERT INTO scada_connections (
    farm_code,
    name,
    protocol,
    server_ip,
    server_port,
    casdu_address,
    originator_address,
    ioa_points,
    upload_target_ioa,
    fetch_interval,
    poll_url,
    is_enabled,
    status,
    status_message,
    last_error,
    created_at,
    updated_at
) VALUES
('CF',   'Huize Cangfang SCADA Simulator',       'c104', 'wind-power-staging-scada-simulator', 2404, 1, 0, '{"16385": "M_ME_NC_1"}', 16385, 60, NULL, TRUE, 'stopped', NULL, NULL, NOW(), NOW()),
('BNJ',  'Huize Bainijing SCADA Simulator',      'c104', 'wind-power-staging-scada-simulator', 2404, 1, 0, '{"16386": "M_ME_NC_1"}', 16386, 60, NULL, TRUE, 'stopped', NULL, NULL, NOW(), NOW()),
('SDS',  'Mile Shidongshan SCADA Simulator',     'c104', 'wind-power-staging-scada-simulator', 2404, 1, 0, '{"16387": "M_ME_NC_1"}', 16387, 60, NULL, TRUE, 'stopped', NULL, NULL, NOW(), NOW()),
('DPLZ', 'Malong Doupoliangzi SCADA Simulator',  'c104', 'wind-power-staging-scada-simulator', 2404, 1, 0, '{"16388": "M_ME_NC_1"}', 16388, 60, NULL, TRUE, 'stopped', NULL, NULL, NOW(), NOW()),
('ZYX',  'Zhuyuanxi SCADA Simulator',            'c104', 'wind-power-staging-scada-simulator', 2404, 1, 0, '{"16389": "M_ME_NC_1"}', 16389, 60, NULL, TRUE, 'stopped', NULL, NULL, NOW(), NOW())
ON CONFLICT (farm_code) DO UPDATE SET
    name = EXCLUDED.name,
    protocol = EXCLUDED.protocol,
    server_ip = EXCLUDED.server_ip,
    server_port = EXCLUDED.server_port,
    casdu_address = EXCLUDED.casdu_address,
    originator_address = EXCLUDED.originator_address,
    ioa_points = EXCLUDED.ioa_points,
    upload_target_ioa = EXCLUDED.upload_target_ioa,
    fetch_interval = EXCLUDED.fetch_interval,
    poll_url = EXCLUDED.poll_url,
    is_enabled = EXCLUDED.is_enabled,
    status = 'stopped',
    status_message = NULL,
    last_error = NULL,
    updated_at = NOW();
